#!/usr/bin/env python3
"""Extract mesh from a 3MF file and write base64-encoded binary for embedding in TypeScript.

Output binary format:
  4 bytes: nVerts (uint32 LE)
  4 bytes: nTris (uint32 LE)
  nVerts * 12 bytes: vertices as float32 XYZ (LE), translated so Z=0 is bottom
  nTris * 12 bytes: triangle vertex indices as uint32 (LE)
"""

import sys, struct, zipfile, base64, xml.etree.ElementTree as ET

def extract(input_3mf: str, output_ts: str, var_name: str, z_offset: float = 0.0):
    with zipfile.ZipFile(input_3mf) as z:
        obj_paths = [n for n in z.namelist() if n.startswith('3D/Objects/') and n.endswith('.model')]
        assert obj_paths, "No object models found"
        data = z.read(obj_paths[0])

    root = ET.fromstring(data)
    ns = {'m': 'http://schemas.microsoft.com/3dmanufacturing/core/2015/02'}

    verts = [(float(v.get('x')), float(v.get('y')), float(v.get('z')) + z_offset)
             for v in root.findall('.//m:vertex', ns)]
    tris  = [(int(t.get('v1')), int(t.get('v2')), int(t.get('v3')))
             for t in root.findall('.//m:triangle', ns)]

    nVerts, nTris = len(verts), len(tris)
    print(f"Vertices: {nVerts}, Triangles: {nTris}")

    buf = bytearray()
    buf += struct.pack('<II', nVerts, nTris)
    for x, y, z in verts:
        buf += struct.pack('<fff', x, y, z)
    for v1, v2, v3 in tris:
        buf += struct.pack('<III', v1, v2, v3)

    b64 = base64.b64encode(bytes(buf)).decode('ascii')
    print(f"Binary size: {len(buf):,} bytes → base64: {len(b64):,} chars")

    # Write as TS constant, wrapped at 76 chars per line
    lines = [b64[i:i+76] for i in range(0, len(b64), 76)]
    ts_lines = [f'export const {var_name} =\n']
    ts_lines += [f'  "{line}" +\n' for line in lines[:-1]]
    ts_lines += [f'  "{lines[-1]}";\n']

    with open(output_ts, 'w') as f:
        f.write('// Auto-generated by scripts/extract-3mf-mesh.py — do not edit manually\n')
        f.write('// Source: Gridfinity bin 6x3x6 Dymo Tag Maker\n')
        f.write('// Mesh format: 4B nVerts + 4B nTris + nVerts*12B float32xyz + nTris*12B uint32 indices\n')
        f.write('// Z-translated so Z=0 is the bottom of the print\n')
        f.writelines(ts_lines)

    print(f"Written to {output_ts}")


if __name__ == '__main__':
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <input.3mf> <output.ts> [var_name] [z_offset]")
        sys.exit(1)
    input_3mf = sys.argv[1]
    output_ts = sys.argv[2]
    var_name = sys.argv[3] if len(sys.argv) > 3 else 'MESH_B64'
    z_offset = float(sys.argv[4]) if len(sys.argv) > 4 else 0.0
    extract(input_3mf, output_ts, var_name, z_offset)
